export const Permissions = {
  CLIENTS_NAVIGATE: 'clients.navigate',
  CLIENTS_LIST: 'clients.list',
  CLIENTS_VIEW: 'clients.view',
  CLIENTS_TYPE_LIST: 'clients.type.list',
  CLIENTS_CREATE: 'clients.create',
  CLIENTS_UPDATE: 'clients.update',
  CLIENTS_DELETE: 'clients.delete',

  PRODUCTS_NAVIGATE: 'products.navigate',
  PRODUCTS_LIST: 'products.list',
  PRODUCTS_VIEW: 'products.view',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_UPDATE: 'products.update',
  PRODUCTS_DELETE: 'products.delete',
  PRODUCTS_STOCK_RESERVED: 'products.stock.reserved',
  PRODUCTS_STOCK_REAL: 'products.stock.real',
  PRODUCTS_CATEGORIES_LIST: 'products.categories.list',
  PRODUCTS_CATEGORIES_CREATE: 'products.categories.create',
  PRODUCTS_CATEGORIES_DELETE: 'products.categories.delete',

  DELIVERY_NOTES_NAVIGATE: 'delivery-notes.navigate',
  DELIVERY_NOTES_LIST: 'delivery-notes.list',
  DELIVERY_NOTES_VIEW: 'delivery-notes.view',
  DELIVERY_NOTES_CREATE: 'delivery-notes.create',
  DELIVERY_NOTES_UPDATE: 'delivery-notes.update',
  DELIVERY_NOTES_DELETE: 'delivery-notes.delete',
  DELIVERY_NOTES_DELIVER: 'delivery-notes.deliver',
  DELIVERY_NOTES_CANCEL: 'delivery-notes.cancel',

  USERS_NAVIGATE: 'users.navigate',
  USERS_LIST: 'users.list',
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
};
